// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvTraf-poAziSy2xuZXTP2-xw7nfOZ32U',
    appId: '1:901525297568:web:b56a4645dce2f7ac2c2cc5',
    messagingSenderId: '901525297568',
    projectId: 'fitathome-copy',
    authDomain: 'fitathome-copy.firebaseapp.com',
    storageBucket: 'fitathome-copy.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0ttIKBIKkBgrmpvFLWA2RJ1L7pZdYXLQ',
    appId: '1:901525297568:android:1b2c50598b8876572c2cc5',
    messagingSenderId: '901525297568',
    projectId: 'fitathome-copy',
    storageBucket: 'fitathome-copy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVDyi4y848VDEeGG_LelHScF53frGDtU4',
    appId: '1:901525297568:ios:d866f410b374ac3f2c2cc5',
    messagingSenderId: '901525297568',
    projectId: 'fitathome-copy',
    storageBucket: 'fitathome-copy.appspot.com',
    iosClientId: '901525297568-aksdknmpl04ltb4tho2fa9b90qov7dn9.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyek',
  );
}
